"""empty message

Revision ID: 365f4187375f
Revises: 8230eca9b5e0
Create Date: 2021-10-18 22:21:21.470625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365f4187375f'
down_revision = '8230eca9b5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('country_full', sa.String(length=128), nullable=False),
    sa.Column('country_abrv', sa.String(length=128), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('previous_points', sa.Float(), nullable=False),
    sa.Column('rank_change', sa.Integer(), nullable=False),
    sa.Column('confederation', sa.String(length=128), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('rank')
    )
    op.drop_table('fifa_ranking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fifa_ranking',
    sa.Column('rank', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_full', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('counyry_abrv', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('total_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_points', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rank_change', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cur_year_avg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cur_year_avg_weighted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_year_avg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_year_avg_weighted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('two_year_ago_avg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('two_year_ago_weighted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('three_year_ago_avg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('three_year_ago_weighted', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confederation', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('rank_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('rank', name='fifa_ranking_pkey')
    )
    op.drop_table('ranking')
    # ### end Alembic commands ###
