"""empty message

Revision ID: 8123813417fc
Revises: 365f4187375f
Create Date: 2021-10-20 00:13:37.947102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8123813417fc'
down_revision = '365f4187375f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fifa_ranking',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('country_full', sa.String(length=128), nullable=False),
    sa.Column('country_abrv', sa.String(length=128), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('previous_points', sa.Float(), nullable=True),
    sa.Column('rank_change', sa.Float(), nullable=True),
    sa.Column('cur_year_avg', sa.Float(), nullable=True),
    sa.Column('cur_year_avg_weighted', sa.Float(), nullable=True),
    sa.Column('last_year_avg', sa.Float(), nullable=True),
    sa.Column('last_year_avg_weighted', sa.Float(), nullable=True),
    sa.Column('two_year_ago_avg', sa.Float(), nullable=True),
    sa.Column('two_year_ago_weighted', sa.Float(), nullable=True),
    sa.Column('three_year_ago_avg', sa.Float(), nullable=True),
    sa.Column('three_year_ago_weighted', sa.Float(), nullable=True),
    sa.Column('confederation', sa.String(length=128), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    op.create_table('worldcup2018',
    sa.Column('team', sa.String(length=128), nullable=False),
    sa.Column('Group', sa.String(length=128), nullable=False),
    sa.Column('first_match', sa.String(length=128), nullable=False),
    sa.Column('second_match', sa.String(length=128), nullable=False),
    sa.Column('third_match', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('team')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worldcup2018')
    op.drop_table('fifa_ranking')
    # ### end Alembic commands ###
