"""empty message

Revision ID: 8230eca9b5e0
Revises: a3840b4fe0b5
Create Date: 2021-10-18 19:22:26.865765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8230eca9b5e0'
down_revision = 'a3840b4fe0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fifa_ranking',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('country_full', sa.String(length=128), nullable=False),
    sa.Column('counyry_abrv', sa.String(length=128), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('previous_points', sa.Integer(), nullable=True),
    sa.Column('rank_change', sa.Integer(), nullable=True),
    sa.Column('cur_year_avg', sa.Integer(), nullable=True),
    sa.Column('cur_year_avg_weighted', sa.Integer(), nullable=True),
    sa.Column('last_year_avg', sa.Integer(), nullable=True),
    sa.Column('last_year_avg_weighted', sa.Integer(), nullable=True),
    sa.Column('two_year_ago_avg', sa.Integer(), nullable=True),
    sa.Column('two_year_ago_weighted', sa.Integer(), nullable=True),
    sa.Column('three_year_ago_avg', sa.Integer(), nullable=True),
    sa.Column('three_year_ago_weighted', sa.Integer(), nullable=True),
    sa.Column('confederation', sa.String(length=128), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('rank')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fifa_ranking')
    # ### end Alembic commands ###
