"""empty message

Revision ID: e5fd01e0ee7d
Revises: 8123813417fc
Create Date: 2021-10-20 08:22:53.640431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fd01e0ee7d'
down_revision = '8123813417fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('average_rank', sa.Float(), nullable=False),
    sa.Column('rank_difference', sa.Integer(), nullable=False),
    sa.Column('point_difference', sa.Float(), nullable=False),
    sa.Column('is_stake', sa.Boolean(), nullable=False),
    sa.Column('is_one', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    # ### end Alembic commands ###
