"""empty message

Revision ID: f272946ec91b
Revises: e5fd01e0ee7d
Create Date: 2021-10-20 16:30:50.552327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f272946ec91b'
down_revision = 'e5fd01e0ee7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rankings_feature',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('rank_date', sa.Date(), nullable=False),
    sa.Column('rank', sa.Float(), nullable=False),
    sa.Column('country_full', sa.String(length=128), nullable=False),
    sa.Column('country_abrv', sa.String(length=128), nullable=False),
    sa.Column('cur_year_avg_weighted', sa.Float(), nullable=False),
    sa.Column('two_year_avg_weighted', sa.Float(), nullable=False),
    sa.Column('three_year_avg_weighted', sa.Float(), nullable=False),
    sa.Column('weighted_points', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rankings_feature')
    # ### end Alembic commands ###
