"""empty message

Revision ID: 7edb7c8e572b
Revises: 
Create Date: 2021-08-06 11:18:47.065791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edb7c8e572b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('country_full', sa.String(length=128), nullable=False),
    sa.Column('country_abrv', sa.String(length=64), nullable=True),
    sa.Column('total_points', sa.Float(), nullable=True),
    sa.Column('previous_points', sa.Float(), nullable=True),
    sa.Column('rank_changed', sa.Integer(), nullable=True),
    sa.Column('confederation', sa.String(length=64), nullable=True),
    sa.Column('rank_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('rank')
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=128), nullable=False),
    sa.Column('away_team', sa.String(length=128), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('tournament', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('neutral', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('ranking')
    # ### end Alembic commands ###
